#!/bin/bash
# Extract Any File Compress
# by wajatmaka
# DGH
# blog.wajatmaka.com

OPTION=$1;
DATA=$2;


function Extract:File(){

	Detect_GZIP=`file -b $DATA | grep -i "gzip" | wc -l 2> /dev/null` 
	Detect_BZIP=`file -b $DATA | grep -i "bzip2" | wc -l  2> /dev/null` 
	Detect_ZIP=`file -b $DATA | grep -i "Zip" | wc -l 2> /dev/null`
	Detect_TARGZ=`file -b $DATA | grep -i "POSIX tar" | wc -l  2> /dev/null`
	Detect_RAR=`file -b $DATA | grep -i "RAR" | wc -l  2> /dev/null`
	Detect_XZ=`file -b $DATA | grep -i "XZ" | wc -l  2> /dev/null`
	Detect_TARBZIP=`file -b $DATA | grep -i "bzip2" | wc -l  2> /dev/null`
	Detect_TARBZIP2=`file -b $DATA | grep -i "bzip2" | wc -l  2> /dev/null`
	Detect_LZMA=`file -b $DATA | grep -i "LZMA" | wc -l  2> /dev/null`
	Detect_7ZIP=`file -b $DATA | grep -i "7-zip" | wc -l  2> /dev/null`
	Detect_TARBZ2=`file -b $DATA | grep -i "bzip2" | wc -l  2> /dev/null`

     if [ -f $DATA ] ; then
         case $DATA in
            *.tar.bz2)   
                if [ "$Detect_TARBZIP2" == "1" ]
				then
					echo "EXTRACT DATA BZIP2";
					tar xvjf $DATA
				else
                	echo "File Did Not BZIP2";
                fi   
                ;;
            *.tar.gz)  
            	if [ "$Detect_TARGZ" == "1" ] || [ "$Detect_GZIP" == "1" ]
				then
					echo "EXTRACT DATA TAR ARCHIVE GNU";
					tar xvzf $DATA
				else
                	echo "File Did Not TAR ARCHIVE GNU";
                fi   
                ;;  
            *.lzma)    
            	if [ "$Detect_LZMA" == "1" ]
				then
					echo "EXTRACT DATA LZMA";
					lzma --decompress --force -v $DATA;  
				else
                	echo "File Did Not LZMA";
                fi                  
                ;;
            *.bz2) 
            	if [ "$Detect_TARBZIP2" == "1" ]
				then
					echo "EXTRACT DATA BUNZIP2";
					bunzip2 -d -f -v $DATA   
				else
                	echo "File Did Not BUNZIP2";
                fi      
                ;;
            *.rar)
            	if [ "$Detect_RAR" == "1" ]
				then
					echo "EXTRACT DATA RAR";
					unrar v $DATA 
					unrar x $DATA   
				else
                	echo "File Did Not RAR";
                fi                      
                ;;
            *.gz)
            	if [ "$Detect_GZIP" == "1" ]
				then
					echo "EXTRACT DATA GZIP";
					gunzip --force --verbose $DATA 
				else
                	echo "File Did Not GZIP";
                fi 
                ;;
            *.tar)
            	if [ "$Detect_TARGZ" == "1" ] || [ "$Detect_GZIP" == "1" ]
				then
					echo "EXTRACT DATA TAR ARCHIVE GNU";
					 tar xvf $DATA  
				else
                	echo "File Did Not TAR ARCHIVE GNU";
                fi                      
                ;;
            *.tbz2)
            	if [ "$Detect_TARBZ2" == "1" ] 
				then
					echo "EXTRACT DATA TAR ARCHIVE GNU BZIP2";
					tar xvjf $DATA  
				else
                	echo "File Did Not TAR ARCHIVE GNU BZIP2";
                fi                      
                ;;
            *.tgz)
            	if [ "$Detect_TARGZ" == "1" ] || [ "$Detect_GZIP" == "1" ]
				then
					echo "EXTRACT DATA TAR ARCHIVE GNU GZIP";
					tar xvzf $DATA  
				else
                	echo "File Did Not TAR ARCHIVE GNU GZIP";
                fi                     
                ;;
            *.zip)
            	if [ "$Detect_ZIP" == "1" ] 
				then
					echo "EXTRACT DATA ZIPPER ";
					unzip -v $DATA
					unzip $DATA  
				else
                	echo "File Did Not ZIPPER";
                fi    
                ;;
            *.Z)
            	if [ "$Detect_TARGZ" == "1" ] || [ "$Detect_GZIP" == "1" ]
				then
					echo "EXTRACT DATA UNCOMPRESS GZIP";
					uncompress $DATA 
				else
                	echo "File Did Not UNCOMPRESS GZIP";
                fi   
                ;;
            *.7z)
            	if [ "$Detect_7ZIP" == "1" ]
				then
					echo "EXTRACT DATA 7-ZIP";
					7z x $DATA
				else
                	echo "File Did Not 7-ZIP";
                fi          
                ;;
            *)  
                echo "'$DATA' cannot be extracted via extract" 
                ;;
        esac
    else
        echo "'$DATA' is not a valid file"
    fi
}

function Compress:File(){
	echo "aha"

}


if [ -z $DATA ]
then
	echo FILE EMPTY;
else
	case $OPTION in
		extract | Extract | e )
		Extract:File;
	    ;;
    	compress | Compress | c )
    	Compress:File;
    	;;
    	*)
		echo "Command for extract  : wjt-compress [extract|Extract|e] [Directory|File] "
		echo "Command for compress : wjt-compress [compress|Compress|c] [Directory|File]"
 		;;
	esac
fi



