#!/bin/bash
# wajatmaka

find -type f -exec md5sum "{}" + | while read data;
do
a=`echo $data| awk -F" " '{print $1}'`
b=`echo $data| awk -F" " '{print substr($0, index($0,$2))}'`
echo "$a $b" > "${b}.md5"
done
